/* Pangu v2 — mock D&D data */

const WORLDS = [
  {
    id: 'faerun',
    name: 'Faerûn',
    motto: 'A continent of sword and spell',
    description: 'The most-walked world. Home to the Sword Coast and its long roads, the dwarven holds of the Spine, the burning gates of Baldur\'s Gate. Trade winds, old grudges, older gods.',
    glyph: 'F',
    accent: '#9b8aff',
    secondary: '#f5c842',
    eraName: 'The Age of Mortals',
    yearLabel: 'DR 1492',
    locations: 12,
    npcs: 23,
    lastVisited: 'Today',
    notes: 'Two open chronicles. The continent is large; the stars, patient.',
  },
  {
    id: 'ravenloft',
    name: 'Ravenloft',
    motto: 'A demiplane of dread, sealed in mist',
    description: 'Not a world but a prison. Pocket-realms of nightmare bound by silvery mist, each ruled by a Darklord who cannot leave. Travellers find their way in. Few find their way out.',
    glyph: 'R',
    accent: '#ff6b6b',
    secondary: '#9b8aff',
    eraName: 'The Mists',
    yearLabel: 'BC 735',
    locations: 4,
    npcs: 9,
    lastVisited: '3d ago',
    notes: 'A small world. The smaller, the heavier the air.',
  },
  {
    id: 'spire',
    name: 'The Spire',
    motto: 'A high-fantasy tower-city, still imagined',
    description: 'A world you have begun to picture but not yet drawn. An empty cradle. The stars are quiet here, awaiting your first mark.',
    glyph: 'S',
    accent: '#3ecfb2',
    secondary: '#9b8aff',
    eraName: 'Pre-history',
    yearLabel: '—',
    locations: 0,
    npcs: 0,
    lastVisited: 'Never',
    notes: 'Empty. Begin where you like.',
  },
];

const CAMPAIGNS = [
  {
    id: 'phandelver',
    worldId: 'faerun',
    name: 'The Lost Mines of Phandelver',
    motto: 'A pact carved in dwarven stone',
    description: 'A caravan of supplies disappears on the road to Phandalin. What begins as a routine errand unravels into a hunt for the lost wealth of the Phandelver\'s Pact.',
    setting: 'Sword Coast · Forgotten Realms',
    system: 'D&D 5e',
    status: 'active',
    type: 'campaign',
    chapter: 4,
    chapterTotal: 9,
    chapterName: 'The Spider\'s Web',
    sessionCount: 12,
    playtimeHours: 46,
    playerCount: 4,
    nextSession: 'Sun · 7:30 PM',
    lastPlayedLabel: 'Tuesday past',
    lastNote: 'Lyria identified the glow on the recovered map as moonlit rune-keys of pre-Sundering make.',
    accent: '#9b8aff',
    glyph: 'P',
    locations: 8,
    npcs: 15,
  },
  {
    id: 'curse',
    worldId: 'ravenloft',
    name: 'Curse of Strahd',
    motto: 'The mists do not return their travellers',
    description: 'A gothic horror lurking in the mists of Barovia. The vampire lord watches from his castle on the cliff — and waits.',
    setting: 'Barovia · Ravenloft',
    system: 'D&D 5e',
    status: 'active',
    type: 'campaign',
    lastPlayedLabel: '3d ago',
    lastNote: 'The first villager of Barovia would not meet the party’s eyes. Then he closed his door.',
    chapter: 2,
    chapterTotal: 11,
    chapterName: 'The Village of Barovia',
    sessionCount: 5,
    playtimeHours: 18,
    playerCount: 5,
    nextSession: 'Wed · 8:00 PM',
    accent: '#ff6b6b',
    glyph: 'S',
    locations: 4,
    npcs: 9,
  },
  {
    id: 'avernus',
    worldId: 'faerun',
    type: 'campaign',
    lastPlayedLabel: '2 weeks past',
    lastNote: 'The Hellrider helms went cold the moment they crossed the threshold.',
    name: 'Descent into Avernus',
    motto: 'Hell is a contract you cannot unsign',
    description: 'The frontier city of Elturel has vanished into the Nine Hells. The party must descend into Avernus to bring it back — or fall trying.',
    setting: 'Baldur\'s Gate · Avernus',
    system: 'D&D 5e',
    status: 'paused',
    chapter: 0,
    chapterTotal: 8,
    chapterName: 'A Tale of Two Cities',
    sessionCount: 2,
    playtimeHours: 8,
    playerCount: 4,
    nextSession: 'On hiatus',
    accent: '#f5c842',
    glyph: 'A',
    locations: 2,
    npcs: 4,
  },
  {
    id: 'skullport',
    worldId: null,
    type: 'oneshot',
    name: 'A Single Night in Skullport',
    motto: 'Three hours below sea level',
    description: 'A oneshot. The party — strangers to one another — wakes in the Port of Shadows beneath Waterdeep. They have until dawn to leave alive.',
    setting: 'Skullport · Beneath Waterdeep',
    system: 'D&D 5e',
    status: 'draft',
    chapter: 0,
    chapterTotal: 1,
    chapterName: 'One Night',
    sessionCount: 0,
    playtimeHours: 0,
    playerCount: 4,
    nextSession: 'Fri · 9:00 PM',
    lastPlayedLabel: 'Not yet begun',
    lastNote: '',
    accent: '#3ecfb2',
    glyph: '☾',
    locations: 1,
    npcs: 3,
  },
];

const CHARACTERS = [
  {
    id: 'lyria',
    name: 'Lyria Moonweaver',
    race: 'High Elf', class: 'Wizard', subclass: 'School of Divination',
    level: 5, xp: 6500, xpNext: 14000,
    campaignId: 'phandelver',
    glyph: '✦',
    accent: '#9b8aff',
    hp: 28, maxHp: 32, ac: 14, speed: 30, init: '+3', prof: '+3',
    stats: { str: 8, dex: 16, con: 14, int: 18, wis: 13, cha: 11 },
    saves: ['int', 'wis'],
    backstory: 'Last of the Moonweavers of Evereska, Lyria left the Silver Groves seeking knowledge lost in the Great Cataclysm. She carries a spellbook bound in dragonhide — a family heirloom that whispers in a tongue she does not yet understand.',
    traits: [
      { name: 'Portent', desc: 'Roll two d20s at dawn. You may replace any roll made later in the day with one of these.' },
      { name: 'Arcane Recovery', desc: 'Once per day on a short rest, recover spell slots totaling half your wizard level.' },
      { name: 'Darkvision', desc: 'See in dim light within 60 ft as if bright; in darkness as if dim.' },
    ],
    spells: [
      { level: 3, name: 'Fireball', school: 'Evocation', range: '150 ft', desc: 'A bright streak flashes from your finger to a point you choose and blossoms with a low roar into an explosion of flame. Each creature in a 20-ft sphere makes a Dex save (8d6 fire).' },
      { level: 2, name: 'Misty Step', school: 'Conjuration', range: 'Self', desc: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.' },
      { level: 1, name: 'Shield', school: 'Abjuration', range: 'Self', desc: '+5 AC until the start of your next turn, including against the triggering attack.' },
      { level: 1, name: 'Magic Missile', school: 'Evocation', range: '120 ft', desc: 'Three glowing darts of magical force. Each dart hits a creature you can see (1d4+1 force).' },
    ],
    inventory: [
      { name: 'Spellbook (dragonhide)', type: 'Arcane focus', qty: 1, rarity: 'rare' },
      { name: 'Dagger', type: 'Weapon · finesse', qty: 1, rarity: 'common' },
      { name: 'Quarterstaff', type: 'Weapon', qty: 1, rarity: 'common' },
      { name: 'Potion of Healing', type: 'Consumable · 2d4+2', qty: 3, rarity: 'common' },
      { name: 'Pearl of Power', type: 'Wondrous item', qty: 1, rarity: 'uncommon' },
      { name: 'Component Pouch', type: 'Equipment', qty: 1, rarity: 'common' },
    ],
    gold: 184, silver: 32, copper: 56,
  },
  {
    id: 'thokk',
    name: 'Thokk Stoneheart',
    race: 'Mountain Dwarf', class: 'Fighter', subclass: 'Battle Master',
    level: 5, xp: 7200, xpNext: 14000,
    campaignId: 'phandelver',
    glyph: '⚒',
    accent: '#f5c842',
    hp: 48, maxHp: 50, ac: 18, speed: 25, init: '+1', prof: '+3',
    stats: { str: 17, dex: 12, con: 16, int: 10, wis: 13, cha: 8 },
    saves: ['str', 'con'],
    backstory: 'A clan-honored shield of Citadel Adbar. Thokk left his hold not in shame but in oath — to recover the rune-axe of his great-grandsire from the Wave Echo Cave. He speaks little. His axe speaks for him.',
    traits: [
      { name: 'Combat Superiority', desc: 'Four maneuvers, four d8 superiority dice you regain on a short or long rest.' },
      { name: 'Second Wind', desc: '1d10+5 self-heal as a bonus action, once per short rest.' },
      { name: 'Dwarven Resilience', desc: 'Advantage on saves vs poison; resistance to poison damage.' },
    ],
    spells: [],
    inventory: [
      { name: 'Rune Axe of Adbar', type: 'Weapon · +1, sentinel', qty: 1, rarity: 'rare' },
      { name: 'Shield', type: 'Armor', qty: 1, rarity: 'common' },
      { name: 'Plate Mail', type: 'Heavy Armor', qty: 1, rarity: 'common' },
      { name: 'Throwing Hammer', type: 'Weapon · ranged', qty: 4, rarity: 'common' },
      { name: 'Potion of Healing', type: 'Consumable', qty: 2, rarity: 'common' },
    ],
    gold: 121, silver: 16, copper: 8,
  },
  {
    id: 'elowen',
    name: 'Elowen Ashvale',
    race: 'Wood Elf', class: 'Ranger', subclass: 'Hunter',
    level: 4, xp: 4800, xpNext: 6500,
    campaignId: 'phandelver',
    glyph: '❦',
    accent: '#3ecfb2',
    hp: 36, maxHp: 38, ac: 15, speed: 35, init: '+4', prof: '+2',
    stats: { str: 13, dex: 18, con: 14, int: 12, wis: 16, cha: 10 },
    saves: ['str', 'dex'],
    backstory: 'Tracker for the Emerald Enclave. Elowen reads the wood the way scholars read books. Where she walks, the ash of burned villages tells her stories.',
    traits: [
      { name: 'Favored Enemy', desc: 'Advantage on Survival to track and Intelligence checks to recall information about humanoids (Drow).' },
      { name: 'Colossus Slayer', desc: 'Extra 1d8 damage to any creature below its hit point maximum (once per turn).' },
      { name: 'Mask of the Wild', desc: 'Attempt to hide when lightly obscured by foliage, weather, or rain.' },
    ],
    spells: [
      { level: 1, name: 'Hunter\'s Mark', school: 'Divination', range: '90 ft', desc: 'Choose a creature you can see; deal an extra 1d6 damage on attacks against it. Advantage on Wis (Perception/Survival) checks to find it.' },
      { level: 1, name: 'Cure Wounds', school: 'Evocation', range: 'Touch', desc: 'A creature you touch regains 1d8+3 hit points.' },
    ],
    inventory: [
      { name: 'Longbow', type: 'Weapon · ranged', qty: 1, rarity: 'common' },
      { name: 'Quiver of Arrows', type: 'Ammunition · 24', qty: 1, rarity: 'common' },
      { name: 'Shortsword', type: 'Weapon · finesse', qty: 2, rarity: 'common' },
      { name: 'Leather Armor', type: 'Light Armor', qty: 1, rarity: 'common' },
      { name: 'Hunting Trap', type: 'Tool', qty: 1, rarity: 'common' },
    ],
    gold: 76, silver: 41, copper: 12,
  },
  {
    id: 'kael',
    name: 'Kael Ravencrest',
    race: 'Human (Variant)', class: 'Rogue', subclass: 'Arcane Trickster',
    level: 4, xp: 5100, xpNext: 6500,
    campaignId: 'phandelver',
    glyph: '☾',
    accent: '#6ba7ff',
    hp: 24, maxHp: 32, ac: 15, speed: 30, init: '+5', prof: '+2',
    stats: { str: 10, dex: 17, con: 14, int: 16, wis: 12, cha: 13 },
    saves: ['dex', 'int'],
    backstory: 'Once an orphan of the Waterdhavian alleys, Kael grew up under the wing of the Zhentarim — until the day he stole something they wanted back. He now keeps three steps ahead and one knife close.',
    traits: [
      { name: 'Sneak Attack', desc: 'Once per turn, deal an extra 2d6 damage when you have advantage, or when an ally is within 5 ft of the target.' },
      { name: 'Cunning Action', desc: 'Bonus action to Dash, Disengage, or Hide.' },
      { name: 'Mage Hand Legerdemain', desc: 'Your invisible mage hand can pick locks, disarm traps, pickpocket, and stow objects.' },
    ],
    spells: [
      { level: 1, name: 'Disguise Self', school: 'Illusion', range: 'Self', desc: 'You change appearance — clothing, armor, and other belongings — for up to 1 hour.' },
      { level: 0, name: 'Mage Hand', school: 'Conjuration', range: '30 ft', desc: 'A spectral hand at a point you choose; you can use an action to manipulate it.' },
    ],
    inventory: [
      { name: 'Daggers (paired)', type: 'Weapon · finesse, thrown', qty: 4, rarity: 'common' },
      { name: 'Hand Crossbow', type: 'Weapon · ranged', qty: 1, rarity: 'common' },
      { name: 'Thieves\' Tools', type: 'Tool · prof', qty: 1, rarity: 'common' },
      { name: 'Hooded Cloak', type: 'Equipment', qty: 1, rarity: 'common' },
      { name: 'Forgery Kit', type: 'Tool', qty: 1, rarity: 'common' },
    ],
    gold: 312, silver: 8, copper: 24,
  },
];

const LOCATIONS = [
  { id: 'phandalin', name: 'Phandalin', type: 'Town', region: 'Sword Coast', x: 32, y: 58, campaignId: 'phandelver',
    desc: 'A mining outpost rebuilt on the bones of a ruined city. Four hundred souls under the shadow of the Redbrand bandits.',
    population: 412, climate: 'Temperate', notes: 'Last visited session 11' },
  { id: 'cragmaw', name: 'Cragmaw Hideout', type: 'Cave', region: 'Sword Mountains', x: 22, y: 38, campaignId: 'phandelver',
    desc: 'A goblin warren guarding the road. The trees here grow crooked. The wind here does not.',
    population: 14, climate: 'Cold · damp', notes: 'Cleared session 6' },
  { id: 'tresendar', name: 'Tresendar Manor', type: 'Ruin', region: 'Phandalin', x: 38, y: 56, campaignId: 'phandelver',
    desc: 'Burned to its foundations a century past. The cellars beneath are not empty.',
    population: 0, climate: 'Temperate', notes: 'Three unexplored levels remain' },
  { id: 'echo', name: 'Wave Echo Cave', type: 'Dungeon', region: 'Sword Mountains', x: 62, y: 26, campaignId: 'phandelver',
    desc: 'The lost mine of the Phandelver\'s Pact. A great horror is said to walk its lower halls. The walls hum, sometimes, with no source.',
    population: '?', climate: 'Below ground', notes: 'Sealed for 500 years' },
  { id: 'thundertree', name: 'Thundertree', type: 'Ruin', region: 'Neverwinter Wood', x: 14, y: 16, campaignId: 'phandelver',
    desc: 'Abandoned to ash-zombies and a green dragon called Venomfang. The locals will not speak its name.',
    population: 0, climate: 'Cold mist', notes: 'Druid Reidoth lives here' },
  { id: 'conyberry', name: 'Conyberry', type: 'Ruin', region: 'Neverwinter Wood', x: 18, y: 22, campaignId: 'phandelver',
    desc: 'Razed by orcs a generation ago. The bones of its watchtower still stand against the pines.',
    population: 0, climate: 'Cold', notes: 'Banshee Agatha haunts the wood nearby' },
  { id: 'neverwinter', name: 'Neverwinter', type: 'City', region: 'Sword Coast', x: 8, y: 30, campaignId: 'phandelver',
    desc: 'The Jewel of the North. Lord Neverember\'s seat. The party will be paid here, if they live to collect.',
    population: 23000, climate: 'Mild', notes: 'Lord Protector\'s court is open' },
  { id: 'leilon', name: 'Leilon', type: 'Town', region: 'High Road', x: 48, y: 72, campaignId: 'phandelver',
    desc: 'A mining town on the High Road. The mayor pays well for caravan escorts. He pays better for silence.',
    population: 750, climate: 'Temperate', notes: '' },
];

const NPCS = [
  { id: 'gundren', name: 'Gundren Rockseeker', role: 'Patron · Captured', desc: 'Dwarven mining engineer. Owns the rediscovered claim to Wave Echo Cave. Last seen bound and gagged at Cragmaw Castle.', campaignId: 'phandelver', mood: 'urgent' },
  { id: 'sildar', name: 'Sildar Hallwinter', role: 'Lords\' Alliance', desc: 'Veteran knight. Honor like an old oak — bent but unbroken. He fights for those who cannot.', campaignId: 'phandelver', mood: 'ally' },
  { id: 'glasstaff', name: 'Iarno Albrek / Glasstaff', role: 'Antagonist', desc: 'Once of the Lords\' Alliance. Now leader of the Redbrand bandits and a wizard of small but spiteful power.', campaignId: 'phandelver', mood: 'enemy' },
  { id: 'halia', name: 'Halia Thornton', role: 'Zhentarim Agent', desc: 'Phandalin\'s smiling miners\' guildmaster. Her smile is an investment instrument.', campaignId: 'phandelver', mood: 'uncertain' },
  { id: 'reidoth', name: 'Reidoth the Druid', role: 'Hermit · Guide', desc: 'Knows the wood the way a stone knows the river. Will not interfere — but may point.', campaignId: 'phandelver', mood: 'neutral' },
  { id: 'agatha', name: 'Agatha the Banshee', role: 'Spectre', desc: 'A grief that became a wail. She remembers things older than the trees.', campaignId: 'phandelver', mood: 'dangerous' },
];

const QUESTS = [
  { id: 'q1', title: 'Recover Gundren Rockseeker', status: 'active', priority: 'critical', reward: '500 gp + claim share', desc: 'Cragmaw Castle\'s lord, the bugbear King Grol, holds the dwarf. Time runs short.' },
  { id: 'q2', title: 'Decipher the glowing map', status: 'active', priority: 'major', reward: 'Knowledge', desc: 'The map glows under moonlight. The marks resemble dwarven trail-runes from before the Sundering.' },
  { id: 'q3', title: 'Clear the Redbrand presence in Phandalin', status: 'completed', priority: 'major', reward: '200 gp + town favor', desc: 'Tresendar Manor was burned down to the cellars. Glasstaff escaped — for now.' },
  { id: 'q4', title: 'Answer the banshee\'s question', status: 'active', priority: 'minor', reward: 'Truthful answer in return', desc: 'Agatha will answer a single question truthfully — if you bring her a gift she finds becoming.' },
  { id: 'q5', title: 'Survey the Wave Echo cavern entrance', status: 'pending', priority: 'major', reward: '—', desc: 'The party has the map but not the courage. Yet.' },
];

const CHAPTERS = [
  { num: 1, name: 'Goblin Arrows', summary: 'The party met on the road to Phandalin and was ambushed by Cragmaw goblins.', date: 'Mar 14', status: 'past' },
  { num: 2, name: 'Phandalin', summary: 'Arrived in town. Met Sildar. Learned of the Redbrand thugs and their hidden master.', date: 'Mar 21', status: 'past' },
  { num: 3, name: 'The Redbrand Hideout', summary: 'Tresendar Manor cellars were cleared. Glasstaff escaped through a portal.', date: 'Apr 04', status: 'past' },
  { num: 4, name: 'The Spider\'s Web', summary: 'Following Reidoth\'s lead, the party tracks Glasstaff toward Cragmaw Castle. A glowing map was recovered.', date: 'May 12', status: 'current' },
  { num: 5, name: 'Cragmaw Castle', summary: 'Where the bugbear king holds Gundren. Where iron meets bone.', date: 'TBD', status: 'future' },
  { num: 6, name: 'Wave Echo Cave', summary: 'The lost mine. The Forge of Spells. And the thing that woke when the dwarves dug too deep.', date: 'TBD', status: 'future' },
];

const MONSTERS = [
  { id: 'm1', name: 'Goblin', type: 'Humanoid (goblinoid)', cr: '1/4', size: 'Small', hp: 7, ac: 15, speed: 30,
    stats: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    desc: 'A small black-hearted creature lurking in dark places, raiding caravans by night. Cowards alone — terrors in number.',
    actions: ['Scimitar +4 (1d6+2 slashing)', 'Shortbow +4 (1d6+2 piercing)', 'Nimble Escape — Disengage or Hide as a bonus action'] },
  { id: 'm2', name: 'Bugbear', type: 'Humanoid (goblinoid)', cr: '1', size: 'Medium', hp: 27, ac: 16, speed: 30,
    stats: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    desc: 'Large goblinoid raiders. Strike first, strike hard, vanish into the underbrush.',
    actions: ['Morningstar +4 (2d8+2)', 'Javelin +4 (2d6+2)', 'Brute — melee attacks deal an extra die'] },
  { id: 'm3', name: 'Owlbear', type: 'Monstrosity', cr: '3', size: 'Large', hp: 59, ac: 13, speed: 40,
    stats: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    desc: 'Half owl, half bear, all appetite. Twice the eyes of a predator. Twice the claws.',
    actions: ['Multiattack — Beak + Claws', 'Beak +7 (1d10+5)', 'Claws +7 (2d8+5)', 'Keen Sight & Smell — adv. on Perception (sight/smell)'] },
  { id: 'm4', name: 'Young Green Dragon', type: 'Dragon', cr: '8', size: 'Large', hp: 136, ac: 18, speed: 40,
    stats: { str: 19, dex: 12, con: 17, int: 16, wis: 13, cha: 15 },
    desc: 'Cunning. Patient. Cruel in the way old things are cruel. Speaks five languages, lies in seven.',
    actions: ['Multiattack — Bite + 2 Claws', 'Bite +7 (1d10+4 + 3d6 poison)', 'Poison Breath (Rech. 5–6) — 15-ft cone, 12d6 poison'] },
  { id: 'm5', name: 'Banshee', type: 'Undead', cr: '4', size: 'Medium', hp: 58, ac: 12, speed: 0 /* hover */,
    stats: { str: 1, dex: 14, con: 10, int: 12, wis: 11, cha: 17 },
    desc: 'The grief of an elf-woman, lengthened into a song with no listener.',
    actions: ['Wail (1/day) — 30-ft, 3d6 psychic, DC 13 Con or 0 HP', 'Corrupting Touch +4 (3d6+2 necrotic)'] },
  { id: 'm6', name: 'Doppelganger', type: 'Monstrosity', cr: '3', size: 'Medium', hp: 52, ac: 14, speed: 30,
    stats: { str: 11, dex: 18, con: 14, int: 11, wis: 12, cha: 14 },
    desc: 'It was your friend an hour ago. It is not now.',
    actions: ['Multiattack — 2 slams', 'Slam +6 (1d6+4)', 'Shapechanger — any small/medium humanoid', 'Read Thoughts — 60-ft range'] },
];

const SETTINGS_DEFAULT = {
  accent: 'violet',
  density: 'standard',
  starfield: 'subtle',
  grain: true,
  uppercaseDisplay: true,
};

window.PANGU_DATA = {
  WORLDS, CAMPAIGNS, CHARACTERS, LOCATIONS, NPCS, QUESTS, CHAPTERS, MONSTERS, SETTINGS_DEFAULT,
};
